name: Lifesteal14
version: '${version}'

main: me.sdmannen.lifesteal14.Main
api-version: '1.21'
load: POSTWORLD
commands:
  heartgame:
    description: Main command for HeartGame
    usage: /heartgame
permissions:
  lifesteal14.admin:
    default: op